# Generated by Django 2.2.6 on 2019-11-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagelink', models.CharField(max_length=255)),
                ('tcgplayerid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('gatherertext', models.TextField(max_length=255)),
                ('storeprice', models.FloatField()),
            ],
        ),
    ]
